### ISSUE TITLE
Session de-serialisation on existing session token

### ISSUE THREAD

**Issue by jon-shanks** [appvia/kore-ui#37]
When the app restarts, it is unable to de-serialise the session:

```kore-ui_1                  | Error: Failed to deserialize user out of session
kore-ui_1                  |     at pass (/app/node_modules/passport/lib/authenticator.js:344:19)
kore-ui_1                  |     at Authenticator.deserializeUser (/app/node_modules/passport/lib/authenticator.js:362:5)
kore-ui_1                  |     at SessionStrategy.authenticate (/app/node_modules/passport/lib/strategies/session.js:60:10)
kore-ui_1                  |     at attempt (/app/node_modules/passport/lib/middleware/authenticate.js:361:16)
kore-ui_1                  |     at authenticate (/app/node_modules/passport/lib/middleware/authenticate.js:362:7)
kore-ui_1                  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
kore-ui_1                  |     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
kore-ui_1                  |     at /app/node_modules/express/lib/router/index.js:284:7
kore-ui_1                  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
kore-ui_1                  |     at next (/app/node_modules/express/lib/router/index.js:275:10)```

**Comment by davet1985** [comment]
I've been trying but cannot replicate this issue.

**Comment by davet1985** [comment]
I've tried more to replicate this but I'm not able to.
