### ISSUE TITLE
Error when trying to accept a team invitation link with the wrong user

### ISSUE THREAD

**Issue by bandesz** [appvia/kore-ui#94]
## Error

```
Error: Request failed with status code 406
    at createError (/Users/bandesz/src/github.com/appvia/kore-ui/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/bandesz/src/github.com/appvia/kore-ui/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/bandesz/src/github.com/appvia/kore-ui/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:328:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

## Proposed solution

We should show an error on the UI saying that the invitation link is invalid.

**Comment by davet1985** [comment]
The UI only understands the link to invite any user to a team and not the user-specific link.

Work needs to be done to generate and expose a user-specific invitation link through the UI.

**Comment by bandesz** [comment]
This is the accepting the invitation link part. Here I would only expect that instead of letting the API 406 error through, we should just show the user a message, saying the invitation link is invalid.

**Comment by davet1985** [comment]
> This is the accepting the invitation link part. Here I would only expect that instead of letting the API 406 error through, we should just show the user a message, saying the invitation link is invalid.

I agree. But also we need to give the user a way to generate the user-specific link in the UI.

**Comment by bandesz** [comment]
Works as expected
